name: Unit Tests
on: push
jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-env
    - uses: ./.github/actions/run-test
